name: Cypress Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npx cypress run

      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-test-report
          path: cypress/reports/*
